const guestGroups = {
    "G001": ["Vraj Patel", "Esha Patel"],
    "G002": ["Vrunda Patel"],
    "G003": ["Vrusha Patel"],
    "G004": ["Raj Patel", "Anya Shah"],
    "G005": ["Jignesh Patel", "Erica Patel"],
    "G006": ["Shehul Patel", "Jessica Patel"],
    "G007": ["Jay Patel", "Vibhuti Patel"],
    "G008": ["Shiv Patel"],
    "G009": ["Shreena Patel"],
    "G010": ["Akshar Patel"],
    "G011": ["Pankaj Patel"],
    "G012": ["Jayu Patel"],
    "G013": ["Hemal Patel"],
    "G014": ["Pratham Patel"],
    "G015": ["Harshil Patel", "Himani Patel"],
    "G016": ["Parth Patel", "Prutha Patel"],
    "G017": ["Shreya Patolia", "Samerth Patel"],
    "G018": ["Neelkanth Patel", "Charmi Patel"],
    "G019": ["Khush Patel", "Aagna Patel"],
    "G020": ["Tarun Joshi", "Nishtha Patel"],
    "G021": ["Rudra Patel"],
    "G022": ["Mayur Patel"],
    "G023": ["Shivam Patel"],
    "G024": ["Upsham Naik"],
    "G025": ["Shril Patel", "Nishi Patel"],
    "G026": ["Kirtan Patel", "Ruchika Patel"],
    "G027": ["Hersh Patel"],
    "G028": ["Jasal Patel"],
    "G029": ["Karan Patel"],
    "G030": ["Kajal Patel"],
    "G031": ["Vrushti Dalal"],
    "G032": ["Ajay Parthasarathy"],
    "G033": ["Abhinav Sirohi"],
    "G034": ["Ashka Desai"],
    "G035": ["Misri Patel"],
    "G036": ["Mansi Patel"],
    "G037": ["Shivani Patel"],
    "G038": ["Kavina Patel"],
    "G039": ["Kelly Cuadrado"],
    "G040": ["Khushi Darji"],
    "G041": ["Ria Patel"],
    "G042": ["Vaishnavi Varma"],
};
